### ISSUE TITLE
Refuses to build locally from specific images due to faulty regular expression

### ISSUE THREAD

**Issue by MitschiBoy** [home-assistant/hassio#1091]
Issue #219 isn't totally fixed.
This problem is not fixed for the key "image".

`WARNING (MainThread) [hassio.store.data] Can't read /data/addons/local/my-addon/config.json: does not match regular expression for dictionary value @ data['image']. Got 'dockeruser/nice-app-1.2'`

Current used regular expression: `^[\w{}]+/[\-\w{}]+$`
It should be: `^[\w{}]+/[\-\.\w{}]+$`

- This matches:

	`dockeruser/nice-app`

- This does not match, but should:

	`dockeruser/nice-app-1.2`

_Originally posted by @MitschiBoy in https://github.com/home-assistant/hassio/issues/219#issuecomment-493707048_

**Comment by qJake** [comment]
Bad stale bot! This is still an issue. You can't specify tags in your images when editing a Hass.io addon manifest.

This works: `qjake/my-image`

This doesn't, but should: `qjake/my-image:1.0.0`

It's possible we may need to open an issue in the Hass.io repository if that's the correct place for this to be filed.

**Comment by GregoryHlavac** [comment]
Also valid is

`2026-03-26 00:43:39.820 WARNING (SyncWorker_19) [supervisor.store.data] Can't read /data/addons/local/config.yaml: does not match regular expression ^([a-z0-9][a-z0-9.\-]*(:[0-9]+)?/)*?([a-z0-9{][a-z0-9.\-_{}]*/)*?([a-z0-9{][a-z0-9.\-_{}]*)$ for dictionary value @ data['image']. Got 'ghcr.io/blakeblackshear/frigate:stable-rocm'`

And failing due to this.

**Comment by agners** [comment]
The add-on/apps system uses the image tag for the app version (from the `version` YAML tag). Hence rejecting image names with tags is by design.
