### ISSUE TITLE
Ingress websocket floods logs: Cannot write to closing transport

### ISSUE THREAD

**Issue by OttoWinter** [home-assistant/hassio#1102]
**Home Assistant release with the issue:** 0.93.2
**Operating environment (HassOS/Generic):** HassOS RPi 3B+ 64-bit
**Supervisor logs:**

```text
19-05-29 15:25:31 ERROR (MainThread) [aiohttp.server] Unhandled exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 448, in start
    await resp.write_eof()
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_response.py", line 444, in write_eof
    await self._payload_writer.write_eof(data)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/http_writer.py", line 138, in write_eof
    self._write(chunk)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/http_writer.py", line 67, in _write
    raise ConnectionResetError('Cannot write to closing transport')
ConnectionResetError: Cannot write to closing transport
```

**Description of problem:**

Logs getting spammed for ingress feature.

Reproduce with:

 - Install ESPHome addon (https://esphome.io) - beta version with ingress support
 - Use the dashboard and do some things.
 - Close view.

After that the Hass.io supervisor logs are flooded with the above.

Very likely I'm doing something wrong in my add-on with closing websocket connections, but still I think the exception should be caught and the logs shouldn't be flooded.

**Comment by pvizeli** [comment]
We do only forward anything. That means also we forward the close message and don't close the connection itself until the peer does it. The question is, why the peer or server try to write to a connection they are already closed by other?

**Comment by OttoWinter** [comment]
Yeah that's a bug I agree.

But this issue is about Hass.io spamming the logs - I think even if this happens Hass.io should not be spamming logs with stack traces

**Comment by Lefuneste83** [comment]
I have been struggling with this issue for the past 2 days.
This exception occurs specifically while one of my ESP32 nodemcu32s board is updating throught MQTT. It is a new issue as it was working fine until 2 days ago.

I have tried all sorts of combinations with Hassio restart, DEV and Master branches of ESPHOME, erase flash, change the board... 
Home Assitant version 94.0
Current ESPHOME versions (Dev and master) I do an uninstall before putting a new one.

I still have to reinstall the Home Assitant layer as it seems more or less related to it...

When this occurs : 
1/ the impacted ESP is loosing its connection in the ESPHOME console. It takes about 1 min after booting the board
2/ I get the infamous log message in Hassio log
3/ I get a MQTT disconnect on the CLI of the board

Conf of the ESP32 board : 

```
esphome:
  name: filament
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: "SSID"
  password: "PWD"
  fast_connect: on
  manual_ip:
    static_ip: 192.168.0.XX
    gateway: 192.168.0.XX
    subnet: 255.255.255.0
    dns1: 192.168.0.XX
    dns2: 8.8.8.8
   
# Enable logging
logger:

mqtt:
  broker: 192.168.0.XX
  username: LOGIN
  password: "PWD"
  birth_message:
  will_message:

ota:
  password: "PWD"

esp32_ble_tracker:
  scan_interval: 60s

sensor:
  - platform: wifi_signal
    name: "WiFi Signal Sensor"

  - platform: xiaomi_mijia
    mac_address: 4C:65:A8:XX:XX:XX
    temperature:
      name: "Temperature 1"
    humidity:
      name: "Humidity 1"
    battery_level:
      name: "Battery Level 1"

  - platform: xiaomi_mijia
    mac_address: 4C:65:A8:XX:XX:XX
    temperature:
      name: "Temperature 2"
    humidity:
      name: "Humidity 2"
    battery_level:
      name: "Battery Level 2"
 
  - platform: xiaomi_mijia
    mac_address: 58:2D:34:XX:XX:XX
    temperature:
      name: "Temperature 3"
    humidity:
      name: "Humidity 3"
    battery_level:
      name: "Battery Level 3"
 
  - platform: ble_rssi
    mac_address: 4C:65:A8:D2:6C:96
    name: "RSSI value 1"

  - platform: ble_rssi
    mac_address: 4C:65:A8:D2:76:61
    name: "RSSI value 2"
    
  - platform: ble_rssi
    mac_address: 58:2D:34:33:D8:49
    name: "RSSI value 3"
```

Log in Hassio (running in Docker/Portainer)

```
19-06-06 16:48:01 ERROR (MainThread) [aiohttp.server] Unhandled exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 448, in start
    await resp.write_eof()
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_response.py", line 444, in write_eof
    await self._payload_writer.write_eof(data)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/http_writer.py", line 138, in write_eof
    self._write(chunk)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/http_writer.py", line 67, in _write
    raise ConnectionResetError('Cannot write to closing transport')
ConnectionResetError: Cannot write to closing transport
```

CLI of the device (happening slightly afterwards) : 

```
[18:49:39][D][esp32_ble_tracker:485]:   Address Type: PUBLIC
[18:49:40][W][mqtt:247]: MQTT Disconnected: TCP disconnected.
[18:49:40][I][mqtt:162]: Connecting to MQTT...
[18:49:45][D][esp32_ble_tracker:464]: Found device 50:88:09:2A:6C:11 RSSI=-75
[18:49:45][D][esp32_ble_tracker:485]:   Address Type: RANDOM
[18:49:53][D][esp32_ble_tracker:464]: Found device EF:11:A0:E5:C8:67 RSSI=-67
[18:49:53][D][esp32_ble_tracker:485]:   Address Type: RANDOM
[18:49:53][D][esp32_ble_tracker:487]:   Name: 'N03TY'
[18:49:59][W][mqtt:247]: MQTT Disconnected: TCP disconnected.
[18:49:59][I][mqtt:162]: Connecting to MQTT...
[18:50:15][D][sensor:092]: 'Filament WiFi Signal Sensor': Sending state -30.00000 dB with 0 decimals of accuracy
[18:50:17][W][mqtt:247]: MQTT Disconnected: TCP disconnected.
[18:50:17][I][mqtt:162]: Connecting to MQTT...
```
And on and on... Losing connection reconnecting... Other MQTT devices don't show this issue.


Also while compiling the binary I get this Waring (not sure if it is related) : 

```
.piolibdeps/AsyncMqttClient_ID346/src/AsyncMqttClient.cpp: In constructor 'AsyncMqttClient::AsyncMqttClient()':
.piolibdeps/AsyncMqttClient_ID346/src/AsyncMqttClient.cpp:40:61: warning: format '%x' expects argument of type 'unsigned int', but argument 3 has type 'uint64_t {aka long long unsigned int}' [-Wformat=]
sprintf(_generatedClientId, "esp32%06x", ESP.getEfuseMac());
^
.piolibdeps/AsyncMqttClient_ID346/src/AsyncMqttClient.cpp:40:61: warning: format '%x' expects argument of type 'unsigned int', but argument 3 has type 'uint64_t {aka long long unsigned int}' [-Wformat=]
```

I have managed to make this behaviour happen by accessing or refreshing the ESPHOME page.

From time to time the board reappears connected in the ESPHOME page but disapears again.

I have other devices working perfectly fine with the same system using MQTT connection as well. It seems to be a weird combination of the device loosing connection due to the type of message it is sending and to the underlying Home Assistant/ESPHOME.

**Comment by OttoWinter** [comment]
@Lefuneste83 This bug tracker is only for hass.io issues, not esphome. See esphome's bug tracker for the other issues you see.

The MQTT, connectivity, etc issues have nothing to do with this issue. This issue is solely about the lengthy trace Hass.io prints when ingress tries to write to a closed ws.

**Comment by pvizeli** [comment]
@OttoWinter we can set this error log to debug?

**Comment by OttoWinter** [comment]
@pvizeli Yes, that would be my suggestion - or catch the error and just print the exception message.
