### ISSUE TITLE
Upgrading to 0.50.1 

### ISSUE THREAD

**Issue by myusuf3** [home-assistant/hassio#121]
I tried updating through the ui as well as on the cli and it doesn't seem to work.  I know there was an issue on pypi around the release. 

someone have a fix to upgrade?

**Comment by pratham2003** [comment]
I installed Hass.io for the first time yesterday on my Raspberry PI 3B.. I had the update notification on the 'States' dashboard.. I clicked it, I got some weird error about 'v' not being defined.

I had rebooted it a few times since yesterday now, today I don't see the update notification but my installed version is still 0.50.0 and not 0.50.1

I tried to update through SSH too via 'hassio homeassistant update' but that didn't work.
The CLI responds with the following to the update command.
{
  "result": "ok",
  "data": {}
}

**Comment by pvizeli** [comment]
I have a timeslot for build image in 16 hours. After that we can publish it.

**Comment by myusuf3** [comment]
Can you explain what that means? is another new version coming up?

**Comment by pvizeli** [comment]
We build a docker image for every version and push this to hub.docker.com. After we had push it, you see the new version and can install/update it on your device.

The hardware they I can use to build this image is not my and I have only timeslots they I can use this Hardware to build new versions. On next free timeslot I'll build the new version as image (that take also 4 hours on build it self).

**Comment by pvizeli** [comment]
by the way, there is no 0.50.1 -> https://github.com/home-assistant/home-assistant/releases

**Comment by myusuf3** [comment]
![image](https://user-images.githubusercontent.com/156825/28789367-29704b50-75f3-11e7-9eaf-10bea69ec437.png) Why am I seeing this?
