### ISSUE TITLE
DHT Sensor not working with HASSIO

### ISSUE THREAD

**Issue by matthinc** [home-assistant/hassio#178]
As described here https://community.home-assistant.io/t/dht-sensor-issue-at-startup-after-fresh-installation/24914 the DHT sensor module (https://home-assistant.io/components/sensor.dht/) Is not working correctly with the new version of HASSIO.

It works just fine with HomeAssistant (and without HASSIO).

**Comment by tungmeister** [comment]
I've been having the same issue with the past few versions of Hassio. I've posted a issue [here](https://github.com/home-assistant/home-assistant/issues/9177) #9177 with a work around that you can use for now. There doesn't seem to be any mention of a fix in the 53 release notes, hopefully it'll get sorted soon!

**Comment by gollo** [comment]
This took some digging, but by default the DHT package isn't installed at install time because it fails on some (non-pi) systems. So it's been relying on installing at runtime when the component is configured.  This has probably been working ok on RPi's with hass until now because the required packages (mentioned above) were available. However, the hass docker image for hassio does not have theses packages available to do the dynamic installation.  It seems to me we need to manually add this install into the raspberrypi docker files? Can you comment @pvizeli? I assuming this is only required on RPi installs, does anyone know any different?

**Comment by pvizeli** [comment]
What is the packages that will be needed?

**Comment by gollo** [comment]
This - https://github.com/adafruit/Adafruit_Python_DHT/archive/da8cddf7fb629c1ef4f046ca44f42523c9cf2d11.zip#Adafruit_DHT==1.3.2

You can see it referenced in the sensors/dht.py file.  I already have some Docker code that will install it. If you agree that the machine specific files are the place for it, I will raise a PR...

**Comment by pvizeli** [comment]
I think it should work like: https://github.com/home-assistant/hassio-build/blob/master/homeassistant/generic/Dockerfile#L12-L21

**Comment by sfarzie** [comment]
Can anyone explain me the right steps I've got to do in order to make dht22 to work again?
I've updated to 0.53 and it is still not working

**Comment by pvizeli** [comment]
You need make a layer inside machine dockerfiles that setup the dev env and install this with pip and remove the dev env

**Comment by sfarzie** [comment]
Sorry I don't know how docker works, do you have a link that helps me to understand what to do?

**Comment by pvizeli** [comment]
https://github.com/home-assistant/hassio-build/blob/master/homeassistant/machine/raspberrypi3

**Comment by sfarzie** [comment]
I've seen you're working on it:
https://github.com/home-assistant/hassio-build/pull/29

When are you going to deploy the fix?
Thanks!!!

**Comment by pvizeli** [comment]
Next home-assistant release -> 0.54

**Comment by bramschats** [comment]
On release 0.62.1 at this moment and it is still not working using this setup:

```
sensor:
  - platform: dht
    sensor: DHT11
    pin: 4
    monitored_conditions:
      - temperature
      - humidity
```

Is it possible to get this working within Hassio?

**Comment by Poratnir** [comment]
Any solution for this to work?

**Comment by GhostViper396** [comment]
any luck?

**Comment by Poratnir** [comment]
any solution for this?

**Comment by TracKer** [comment]
Related issues: https://github.com/home-assistant/home-assistant/issues/15847
But no solution there. The problem is in Adafruit module's platform detection, it thinks that it's running not on Raspberry Pi.
Here is a comment with detailed explanation: https://github.com/home-assistant/home-assistant/issues/15847#issuecomment-414690906

**Comment by Tim3100** [comment]
Also interested in a fix.

**Comment by ornolio** [comment]
I also need it. Thank You
