### ISSUE TITLE
Tellstick in Hass.IO

### ISSUE THREAD

**Issue by Fompa** [home-assistant/hassio#225]
It's seems that using a Tellstick Duo is not working with Hass.IO. Have been reading forums about this issue. 

Any plans on adding this funktion to Hass.IO?

**Comment by pvizeli** [comment]
I have no hardware and can't do that.

But if some one with sysadmin and development skills will do it, I can help him.

**Comment by pvizeli** [comment]
We need now only one that add it into dockerfile...

**Comment by michaeleklof** [comment]
Hi, I have the Tellstick (non Duo) working with OpenHab on an Raspberry Pi 3 currently, and want to use Hass.IO instead, therefore this issue is a show stopper, so I am really interested in getting this working.  

How can I help? I have decent sysadmin and dev skills (but not Python).

**Comment by pvizeli** [comment]
No worry, the hassio/homeassistant integration can be done by me. But you need add the service to https://github.com/home-assistant/hassio-build/blob/master/homeassistant/base/Dockerfile

**Comment by jeena** [comment]
I just bought a Tellstick duo and I can help out too, am doing sysadmin stuff at work and python shouldn't be a problem either. Just need some first pointers of how thy system is build and updated.

**Comment by jeena** [comment]
So it looks like we need to compile the [code](http://developer.telldus.com/wiki/TellStickInstallationSource) during the creation of the docker image?

**Comment by jeena** [comment]
There seem to be prebuild binaries available for Raisin OS here https://github.com/endor-force/tellstick-core-2.1.2_resinos

**Comment by pvizeli** [comment]
We run with Alpine linux and not with yocto linux (aka resinos) on that place

**Comment by jeena** [comment]
Ok, I tried my first stab on this problem https://github.com/jeena/hassio-build/commit/3c2b4e8dd538dd7ffa4eba7e3b243f35de2340a0 my problem right now is that I don't quite understand how I can test build this docker image.

Using plain `docker build .` stops at the first step which uses `sh` because I didn't give it the BUILD_FROM parameter which makes sense. My problem is now that I don't understand the flow on which of the build scripts I'd need to trigger so in the end this docker image would be build so I could test the stuff I'm trying to do.

**Comment by pvizeli** [comment]
https://github.com/home-assistant/hassio-build/tree/master/builder

-> `--homeassistant-base --amd64 --test --docker-hub homeassistant`

**Comment by pvizeli** [comment]
There are some patch available with google for alpine. Maybe you need use this. You can also build libftdi-compat from source before you build tellcore like other library does it above.

Please move that code above into compile section before we install regulary things.

We should also install last stable version and not the trunk version that is tagged as beta

**Comment by jeena** [comment]
Ok thanks I will try that. The latest stable wouldn't compile that is why I chose trunk, but that was on my, perhaps it compiles for Alpine.

**Comment by jeena** [comment]
I'm not sure if I'm doing something wrong or if it's some kind of a bug.

I checked out this repo and ran:

```
cd hassio-build/builder
./create.sh --homeassistant-base --amd64 --test --docker-hub homeassistant
```

after some time I get this error:

```
...
Successfully built caca037178b9
Successfully tagged homeassistant/amd64-builder:20171030
Sending build context to Docker daemon  23.04kB
Step 1/11 : ARG BUILD_FROM
Step 2/11 : FROM $BUILD_FROM
armhf-xenial: Pulling from multiarch/ubuntu-core
8fa72fd9c5d5: Already exists 
111863bd8769: Already exists 
97ba519afe81: Already exists 
ee269b7ebe33: Already exists 
Digest: sha256:d7b678acb636b534cd8ade5dccab3fe66236869abc7ab7f75d71feb2aef79798
Status: Downloaded newer image for multiarch/ubuntu-core:armhf-xenial
 ---> 47ff729cbd0f
Step 3/11 : ARG BUILD_ARCH
 ---> Running in c324caf8f377
 ---> e9e4683da303
Step 4/11 : RUN apt-get update && apt-get install -y         jq         git         python3-setuptools     && rm -rf /var/lib/apt/lists/* ENV LANG C.UTF-8
 ---> Running in 33d1f294bd16
standard_init_linux.go:195: exec user process caused "exec format error"
The command '/bin/sh -c apt-get update && apt-get install -y         jq         git         python3-setuptools     && rm -rf /var/lib/apt/lists/* ENV LANG C.UTF-8' returned a non-zero code: 1
```

**Comment by pvizeli** [comment]
```bash
docker run --rm --privileged homeassistant/amd64-builder --homeassistant-base --amd64 --test --docker-hub homeassistant -r https://github.com/my_repository_fork/ -t homeassistant/base
```

**Comment by bjorne** [comment]
Nice to see this moving forward! Given that I'm interested in seeing this getting in place, I went ahead and did some more stabbing on top of yours @jeena.

@endor-force has been so kind to provide us with all instructions needed to build telldus-core. See the [README](https://github.com/endor-force/tellstick-core-2.1.2_resinos/blob/f1d7dd6460931921c7db8318ce2394254f61c2e5/README.md) and the [build script](https://github.com/endor-force/tellstick-core-2.1.2_resinos/blob/f1d7dd6460931921c7db8318ce2394254f61c2e5/telldus-core-2.1.2_source_resinOS/build.sh#L4) for required build deps.

My branch successfully compiles now; https://github.com/bjorne/hassio-build/tree/telldus-alpine

Unfortunately, the patches must go somewhere so in order to get it to work I've created a branch on top of 2.1.3-beta1, see https://github.com/bjorne/telldus/commit/687da09e5e09172204a98f5524ce737be196d0f9. Alternative solutions would be to get these changes into upstream or apply the patch during installation. What do you think?

Now, I'm completely lost in how to get the homeassistant-base build that I've created onto my raspberry pi hass.io installation to see that telldus works. How can I do that?

**Comment by pvizeli** [comment]
You can make a PR to our repository with this Build part. Look okay for me. Please move the code to suggestion positon to hold the cache correct and the image small :)

![image](https://user-images.githubusercontent.com/15338540/32269650-653d1926-bef3-11e7-9f19-5b56f9623b37.png)

**Comment by Fompa** [comment]
Do I understand this right, what Tellstick now works in Hass.IO version 0.57.2? 

I still got the error message 

The following components and platforms could not be set up:
tellstick

But in the the log I don't get any information about a error with Tellstick.

**Comment by endor-force** [comment]
It is halfway there.. The libraries are compiled in to hass.io now. The service (daemon) is also compiled but it is not started - that is why the error persists. 

There has been disussions whether it should be put as an add-on but then we have a problem with how the python service should communicate with the daemon in the addon.

My suggestion would be to start the already existing service in homeassistant docker and then we have tellstick support in hass.io. But i am waiting on feedback, pros and cons.
