### ISSUE TITLE
can only edit resin-sample once?

### ISSUE THREAD

**Issue by cogneato** [home-assistant/hassio#283]
Editing resin-sample to enable wifi works, but editing it again to disable wifi does not work. Is there something else that needs to be done?

**Comment by frenck** [comment]
Resin does not support (to my knowledge), since the configuration is picked up and stored elsewhere. Removing it from the configuration file, will not remove it from the secondary location.

Not sure, but the lame option, would be to put dummy data into the config file for the WiFi configuration in order to let it fail?

**Comment by cogneato** [comment]
Using dummy data works to kill the wifi connection where deleting the file or removing the data does not. Thanks, @frenck
