### ISSUE TITLE
RFC: add more features to NGINX and enable it by default

### ISSUE THREAD

**Issue by c727** [home-assistant/hassio#325]
users can still use :8123 or connect using the standard ports (so they don't have to remember the port for example)

ideas for ne features:
- support Google domain verification
- support Let's Encrypt verification
- handle emulated hue
- make api usage saver like using user agent filter and url rewrite /fefuszfg8sdgdgbzr8g -> /api/dialogflow?ha_password=secret_password <-- I think this would be also a good topic for a blog post
- maybe SSL can be auto enabeld if certs are available or we simply generate them on the fly
- support panels for other add-ons

maybe @frenck is interested in this project? :stuck_out_tongue_closed_eyes:

**Comment by ciotlosm** [comment]
I think enabling ssl is a bit more complex because you can use either certbot or duckdns addons to do things, and they do it in different ways (talking about bestlibre addons for example). I like bestlibre nginx more because it supports vhost and certbot probe is exposed by default. 

I do agree that nginx enabled by default and mqtt enabled by default is a good approach.
