### ISSUE TITLE
git diff terminal colors not working

### ISSUE THREAD

**Issue by metbril** [home-assistant/hassio#343]
I use git for version controlling my configuration. A `git status` shows colorized output for changed files. But when I use a `git diff .gitignore` the colors are not showing. Instead I get to see the literal escape codes.

Using hassio latest, ssh with different ssh clients from different machines. 

Please note, terminal colors are working in general, but not with git diff.

**Comment by jkeljo** [comment]
I ran into this just now and investigated a bit. The issue is that `git` by default uses `less` to page the output of its commands, and `less` on Hass.io is a stripped-down version provided by `busybox` that does not have color support.

Two workarounds:
1. Disable paging in git commands (`git config --global core.pager cat`)
2. Install a more full featured `less` (`apk --no-cache add less`)

It would be nice if a future version of Hass.io could ship with a full version of `less` so that this workaround is not necessary.

**Comment by babaliaris** [comment]
It's because git uses by default **less** as a pager.

You can use: https://github.com/dandavison/delta which is extraordinary!

For installation see: https://dandavison.github.io/delta/get-started.html
