### ISSUE TITLE
homekit controller in 0.68.0 fails on hass.io

### ISSUE THREAD

**Issue by tube0013** [home-assistant/hassio#453]
with homekit-controler enabled per the docs you get this error on statup.
```
Unable to install package homekit==0.6: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-0_5lntts/cffi/
```

**Additional information:**

**Comment by kolossboss** [comment]
+1 same problem. Hassio on Raspberry Pi 3

**Comment by comi8903** [comment]
I’m having the same issue.  0.68.1 did not I fix the issue.

**Comment by HarmlessSaucer** [comment]
I also experienced the same issue as this on Hassio 0.68 and after upgrading to 0.68.1 as per our discussion here:  [Issues with HomeKit](https://community.home-assistant.io/t/issues-with-homekit/51776/11)

`(SyncWorker_6) [homeassistant.util.package] Unable to install package homekit==0.6: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-kedmi3ai/cffi/
ERROR (MainThread) [homeassistant.requirements] Not initializing homekit_controller because could not install requirement homekit==0.6
ERROR (MainThread) [homeassistant.setup] Setup failed for homekit_controller: Could not install all requirements.`

I see the following on the dashboard:
`Invalid Config
The following components and platforms could not be set up:

homekit-controller
Please check your config.`

**Comment by pvizeli** [comment]
Fix with next Home-Assistant Update

**Comment by pvizeli** [comment]
https://github.com/home-assistant/hassio-build/commit/76a13dbf373bd04c1bceefe8a27ad8997f47226a
