### ISSUE TITLE
Built in Repo failure for ADD-ON STORE

### ISSUE THREAD

**Issue by bagobones** [home-assistant/hassio#476]
Home Assistant
0.69.1

Hass.io supervisor
Version | 103.3

Host system
Hostname | hassio
System | Resin OS 2.3.0+rev

ADD-ON store shows no build in ad-dons.

```
18-05-21 07:30:03 INFO (MainThread) [hassio.addons.git] Pull addon https://github.com/home-assistant/hassio-addons repository
18-05-21 07:30:03 ERROR (MainThread) [hassio.addons.git] Can't pull https://github.com/home-assistant/hassio-addons repo: Cmd('git') failed due to: exit code(128)
  cmdline: git pull -v origin
  stderr: 'fatal: Not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).'.
18-05-21 07:30:03 INFO (MainThread) [hassio.addons] Load addons: 0 all - 0 new - 0 remove
```

**Comment by jonathanweinberg** [comment]
Same here. Fresh new install of generic hass.io

Supervisor `103.3`

io.hass.arch | amd64
-- | --
io.hass.type | supervisor
io.hass.version | 103.3

Home Assistant `0.69.1`

io.hass.arch | amd64
-- | --
io.hass.machine | qemux86-64
io.hass.type | homeassistant
io.hass.version | 0.69.1



`18-05-27 02:55:36 ERROR (MainThread) [hassio.addons.git] Can't pull https://github.com/home-assistant/hassio-addons repo: Cmd('git') failed due to: exit code(1)
  cmdline: git pull -v origin.`

This does not happen on my Raspberry Pi 3B that has been upgraded over the past months.

**Comment by pvizeli** [comment]
can you send a dmesg after this failover is seen?

**Comment by timnunes** [comment]
I had this same problem. I fixed it by flashing the .bz2 file instead of unzipping and flashing the .img.

**Comment by cogneato** [comment]
This continues to be a problem that I see with other users. I haven't experienced it myself. After a fresh install, the community repo is present, but the official repo is missing. An example from logs:

```
18-06-13 15:57:48 INFO (MainThread) [hassio.addons.git] Clone addon https://github.com/home-assistant/hassio-addons  repository
18-06-13 15:57:48 ERROR (MainThread) [hassio.addons.git] Can't clone https://github.com/home-assistant/hassio-addons  repo: Cmd('git') failed due to: exit code(128)
  cmdline: git clone --recursive -v https://github.com/home-assistant/hassio-addons  /data/addons/git/fc00ba7d
  stderr: 'Cloning into '/data/addons/git/fc00ba7d'...
fatal: unable to access 'https://github.com/home-assistant/hassio-addons /': The requested URL returned error: 400
'.
18-06-13 15:57:48 ERROR (MainThread) [hassio.addons] Can't load from repository https://github.com/home-assistant/hassio-addons 
18-06-13 15:57:49 INFO (MainThread) [hassio.addons] Load addons: 19 all - 0 new - 0 remove
```

**Comment by pvizeli** [comment]
We speak about resinos?

**Comment by pvizeli** [comment]
Fix with v114
