### ISSUE TITLE
[RFC] Store add-on logs somewhere...

### ISSUE THREAD

**Issue by frenck** [home-assistant/hassio#521]
# Motivation

In case an add-on outputs a lot of line in its log, it becomes impossible to grab or see it...

For example, the community add-ons all support log levels. In case the level is set to `debug`, the output would be rather big and quick.

(This also applies to the supervisor system log).

## Expected behavior

Able to show more history or scroll back to it.
Maybe log into a file (optionally or by default)

## Actual behavior

You can only view the last 100 lines (estimate).

## Steps to reproduce

- Start any add-on with much log output (e.g., Community Example add-on, after like 5 minutes running).
- View add-on log output

## Proposed changes

- Ensure full logs of the last run are available (maybe limited to like a day? or 2?)
- Write them into a log file, or make them available through an API.
- Make the log files available in a more decent way, since they are now shown as text, which makes longer lines harder to view.
- Remove the "refresh" and maybe stream the output of the add-on (websockets?)

## Reference material

Example of how GitLab shows output from a build:
https://gitlab.com/hassio-addons/addon-node-red/-/jobs/74390658

Example of how Travis shows output from a build:
https://travis-ci.org/home-assistant/home-assistant/jobs/394350068

**Comment by frenck** [comment]
I know this is still limited at this point. This is more like a reference / future wish thingy/idea.
It is perfectly fine to leave it in here for some time.

**Comment by pvizeli** [comment]
Yeah, I think the 2 points are possible without a problem. The only limited factor is the driver of logs handler they is in use by docker.

**Comment by ndarilek** [comment]
In the absence of this, how do I debug addons that aren't quite doing what I think they should but produce lots and lots of logs?

I'm building an addon for the Mycroft voice assistant. Mycroft logs a lot by default, and right now when everything isn't working well, I need all the logs I can get. But my addon is failing to start, and because the logs rotate so quickly I can't figure out why. More specifically, a directory in /share that I'm trying to autocreate in my addon's startup script isn't getting created and I can't figure out why, in part because by the time I can look at the logs, they've already scrolled past the likely error condition.

**Comment by HITChris** [comment]
This is also a continuous obstacle for me. Is this still on our radar?
