### ISSUE TITLE
Hassio on RP3 wont restart. API 401 error

### ISSUE THREAD

**Issue by therealnips** [home-assistant/hassio#643]
I added some code to my Hassio just now, clicked the check config button, all ok. I then clicked restart and it warned me on the home screen there was an error so it would restart. The error was:

Log Details (ERROR)
Sat Aug 11 2018 09:40:51 GMT+0100 (British Summer Time)

Hass.io config check API error

Never seen this before, so googled it. People said it was to do with the ssh, so I clicked the hass.io on the left side with the aim of reseting duckdns, but i got this error when clicking on the hass.io button on the left:

Unable to load the panel source: /api/hassio/app/entrypoint.js.

I havent changed anything for days and its been working fine. In fact now its working fine and lets us log in, I just cant restart it or make any changes.

**Comment by frenck** [comment]
Ensure your system is upgraded to the latest and greatest, flush your browser cache and the error should be gone.

This has been a known issue in "older" versions, which have been fixed already.
I'm closing this issue because of that, if you are still experiencing issue, I would advise jumping onto our Discord server.
