### ISSUE TITLE
Move hassio frontend from home-assistant to hassIO 

### ISSUE THREAD

**Issue by sholzmayer** [home-assistant/hassio#801]
Is there any reason why the hassIO administration frontend is deployed via home-assistant? In my opinion a direct integration of the hassIO frontend into the hassIO supervisor or maybe even better as  an hassio-addon would be the more sophisticated way? 

Maybe i want to disable the home assistant frontend (via the hassIO commandline), then the hassIO admin frontend also is no longer available...

**Comment by pvizeli** [comment]
Because we have no UI developer and we need hope every time that some developer there have time to work on the UI. Currently I've a long list of things that we need do and also some project are stooped because we miss a UI developer.

Anyway, the official UI is integrated into Home Assistant because it's one piece that we provide. You can create a add-on with a customer UI, there is no limit.

https://github.com/home-assistant/home-assistant-polymer/issues/1710
