### ISSUE TITLE
Contribution Guide

### ISSUE THREAD

**Issue by cschroeter** [home-assistant/hassio#802]
I would like to participate in this project. Unfortunately it is not clear to me how to setup a proper development environment. Is there any kind of contribution guide oder docs that could help?

**Comment by arsaboo** [comment]
Dev docs are [here](https://developers.home-assistant.io/en/).

**Comment by cschroeter** [comment]
@arsaboo I know - but they are mostly related to Homeassistant not Hass.IO (supervisor).

**Comment by cschroeter** [comment]
There is no developer modus in `updater.json`. Just find something in `/etc # cat /etc/machine-info
CHASSIS=embedded
DEPLOYMENT=production`

**Comment by pvizeli** [comment]
that is inside `/mnt/data/supervisor`. Hass.io/HassOS have his release circle and developer state currently because you can run a stable Hass.io on a developer HassOS and so on.

`docker run --rm --privileged -v ~/.docker:/root/.docker homeassistant/amd64-builder --armhf --supervisor --docker-hub cschroeter -r https://github.com/cschroeter/hassio -b my-test-xy`
