### ISSUE TITLE
DNS issue inside addons / containers

### ISSUE THREAD

**Issue by beloso** [home-assistant/hassio#834]
**Home Assistant release with the issue:**
0.82.1

**Operating environment (HassOS/Generic):**
HassOS

**Supervisor logs:**
18-11-23 07:43:22 INFO (MainThread) [hassio.hassos] Fetch OTA update from https://github.com/home-assistant/hassos/releases/download/1.13/hassos_rpi3-1.13.raucb
18-11-23 07:48:23 WARNING (MainThread) [hassio.hassos] Can't fetch versions from https://github.com/home-assistant/hassos/releases/download/1.13/hassos_rpi3-1.13.raucb:
18-11-23 07:48:27 INFO (SyncWorker_18) [hassio.docker.interface] Clean homeassistant/armhf-addon-duckdns Docker application
18-11-23 07:48:30 INFO (SyncWorker_18) [hassio.docker.addon] Start Docker add-on homeassistant/armhf-addon-duckdns with version 1.5
18-11-23 07:56:14 INFO (SyncWorker_14) [hassio.docker.interface] Clean homeassistant/armhf-addon-duckdns Docker application
18-11-23 07:56:17 INFO (SyncWorker_14) [hassio.docker.addon] Start Docker add-on homeassistant/armhf-addon-duckdns with version 1.5

**Description of problem:**
I have a few addons. One of them is Pi-Hole.
I have set up Pi-Hole to be announced as the DNS for my local network on a OpenWRT router using dhcp options: `6,<Pi-Hole IP Address>`.

Now my addons are not able to resolve Domain Names. But my HassOS host is able to resolve names without any issue.

Is there a way to fix this problem? I don't know what else I can do to debug this.

**Comment by pvizeli** [comment]
Docker uses only the first DNS server from the resolver. Can you post the input of your resolver file?
The Add-on is also not running on bootup, what is happening if you add a second DNS server on DHCP with 8.8.4.4?

**Comment by beloso** [comment]
Output of `/etc/resolv`

```
nameserver 172.30.32.2
options ndots:0
```

If I add a second on the DHCP server it appears to work.

**Comment by pvizeli** [comment]
I mean the HassOS resolver. You say on HassOS it works.

**Comment by beloso** [comment]
How can I check the HassOS resolver?

**Comment by erfind** [comment]
Could this also be causing issues with the Nest integration getting Internal validation issues?

**Comment by frenck** [comment]
@beloso If you are using Pi-hole, it is **very important** to have your Hass.io device configured with a **static** IP address (static, not DHCP assignment/reservation) with an **external** DNS provider.

If you don't do that, you will get issues like described. This is also noted in the Pi-hole add-on documentation.

**Comment by beloso** [comment]
I don't find the instructions of how to do that in the Pi-Hole Repo.
I am not entirely sure I understand what you mean by static IP address with an external DNS provider.

My Hassio has a static local IP address, set with my router.
My Hassio is "exposed" to the internet with the help of DuckDNS.

(Btw, if this is not an Hassio issue, I am okay with closing the ticket, we can move this discussion somewhere else.)

**Comment by frenck** [comment]
@beloso  "My Hassio has a static local IP address, set with my router." -> That is not a static IP address.
Your device still gets his IP address assigned by your router, except, your router assigns the same IP address over and over again. A static IP address is a fixed IP address configured in your device, so it just has it and does no longer depend on your router.

DNS has to be an (static configured) external IP address as well. If you configure it without that, you Pi-hole device itself will become a client to itself... which will cause issues (loops). For example: Hass.io upgrades the Pi-hole add-on (or something is wrong but assume Pi-hole is down). How does Hass.io connect to the internet now?

PS, it is listed as the second note/line in the installation steps of the add-on documentation:

![image](https://user-images.githubusercontent.com/195327/49395015-a2b68c80-f735-11e8-8903-be75a5e3309d.png)

It is also discussed  and answered about a dozen times in the Community forum:
https://community.home-assistant.io/t/community-hass-io-add-on-pi-hole/33817?u=frenck

I understand this might be confusing, a lot of people ran into this. So don't worry 👍 
Check the above forum topic and join us on Discord, where we can explain/help you further directly (instead of a slow chat in a GitHub issue 😉 ).

I would suggest closing this issue until we are sure you are not experiencing a configuration error.

**Comment by beloso** [comment]
Thank you for your very complete response. 
I didn't know about that difference between Static and Router Assigned (even if the same IP). Thank you for clearing that up.

Right now I don't have time to check my configuration. I will do that later this week and I will update with my results. I will boot up discord if I find any troubles.

I am going to close this issue in order not to create additional noise about a potential non-issue.

**Comment by beloso** [comment]
Just to update I did change Pi-Hole to a static address.
I have added the `6,<Pi-Hole IP Address>` option to my OpenWRT router.
So far my addons seem to be working well.

@frenck I am having a problem on Pi-Hole side now. The clients will display as IP addresses. Is there a way to get them to display as their hostname? or the name I set for them in the router?
