### ISSUE TITLE
Addon's device list mapping not updated after device became unavailable

### ISSUE THREAD

**Issue by sibbl** [home-assistant/hassio#835]
# Problem/Motivation

I'm currently migrating from my old Razberry Z-Wave integration to another solution. However, this also means that I want to get rid of the line `dtoverlay=pi3-miniuart-bt` in my `config.txt`.

After that change, my Node-RED addon doesn't start up anymore with the following message:

```
linux runtime spec devices: error gathering device information while adding custom device "/dev/ttys0" "hassio"
```

Apparently `/dev/ttys0` as well as `/dev/ttyAMA0` are not available anymore and the `devices` list for the addon is not updated properly.

Checking the latest snapshot of hassio I see the following `devices` list the Node-RED `addon.json`:

```
"devices": [
      "/dev/mem:/dev/mem:rwm",
      "/dev/ttyS0:/dev/ttyS0:rwm",
      "/dev/ttyAMA0:/dev/ttyAMA0:rwm",
      "/dev/ttyS0:/dev/ttyS0:rwm",
      "/dev/ttyAMA0:/dev/ttyAMA0:rwm",
      "/dev/ttyS0:/dev/ttyS0:rwm",
      "/dev/ttyAMA0:/dev/ttyAMA0:rwm",
      "/dev/ttyS0:/dev/ttyS0:rwm",
      "/dev/ttyAMA0:/dev/ttyAMA0:rwm",
      "/dev/ttyS0:/dev/ttyS0:rwm",
      "/dev/ttyAMA0:/dev/ttyAMA0:rwm",
      "/dev/ttyS0:/dev/ttyS0:rwm",
      "/dev/ttyAMA0:/dev/ttyAMA0:rwm",
      "/dev/ttyS0:/dev/ttyS0:rwm",
      "/dev/ttyAMA0:/dev/ttyAMA0:rwm",
      "/dev/ttyS0:/dev/ttyS0:rwm",
      "/dev/ttyAMA0:/dev/ttyAMA0:rwm",
      "/dev/ttyS0:/dev/ttyS0:rwm",
      "/dev/ttyAMA0:/dev/ttyAMA0:rwm",
      "/dev/ttyS0:/dev/ttyS0:rwm",
      "/dev/ttyAMA0:/dev/ttyAMA0:rwm",
      "/dev/ttyS0:/dev/ttyS0:rwm",
      "/dev/ttyAMA0:/dev/ttyAMA0:rwm",
      "/dev/ttyS0:/dev/ttyS0:rwm",
      "/dev/ttyAMA0:/dev/ttyAMA0:rwm"
    ],
```

## Expected behavior

I'd expect the Node RED addon to start again after some became devices unavailable.

## Actual behavior

The Node RED addon doesn't start when I remove `dtoverlay=pi3-miniuart-bt` from my `config.txt`.

## Steps to reproduce

1. Add `dtoverlay=pi3-miniuart-bt` to the `config.txt` on the boot partition of Raspi 3 hassio.
2. Set up HA with a Node RED addon while checking that `/dev/ttyAMA0` and `/dev/ttyS0` are available
3. Remove the line of step 1 from the `config.txt` again
4. Boot hassio again and wait for the error in the hassio log when it wants to start the Node RED addon

## Workaround

Add the line to the `config.txt` again and the devices are back...

## Proposed changes

I'd expect HassIO to be so dynamic that I can simply change my device list and it will update my containers. At least having a process to update this (even manually via SSH or something) would be helpful.

## Versions

I'm using 
- Raspberry Pi 3b
- Supervisor 140
- HassOS 1.12
- HA 0.82.1
- Node RED v1.1.0

**Comment by wrkn4alivn** [comment]
I got stuck on this, my Z-Wave dongle used to map to /dev/ttyACM0 but now it is on /dev/ttyACM1 and the former system device no longer exists. Node-RED container won't start up. I couldn't figure out how to get it to ignore the obsolete device. What is the workaround?

**Comment by jsiemek** [comment]
Hi,

Simply Creative link from /dev/ttyACM0 to /dev/ttyACM1.

ln -s  /dev/ttyACM0 /dev/ttyACM1


Jarek
W dniu pt., 12.04.2019 o 06:44 wrkn4alivn <notifications@github.com>
napisał(a):

**Comment by wrkn4alivn** [comment]
Thanks for that!

Maybe I'm missing something, but it seems like remapping devices might only be valid until the next time I reboot and/or plug in another USB device. Device mappings can move around without user intention, and I assumed that somehow docker/hassio can be manually but gracefully told to flush old configs and take in the new state of things. Is that possible, and perhaps a better workaround? My total inexperience with docker is showing here.

**Comment by jsiemek** [comment]
Hi,

Are you really using this dev in node-red?

My idea of creating symlink comes from my experience. One day my node-red didn’t want to start and complain about missing /dev/ttyxxxx.
But, I never used any tty in node-red.
I created symlink, node-red started successfully.
Then I restarted it and checker that none of /dev/ttyxxxx are in use, so I deleted created sum link and node-red started without errors. I really don’t know what was the root cause of this.

So if you are NOT using any /dev/ttyxxx in node-red this could help you. If you are using them, try to use /dev/by-id/ which are more persistent then /dev/tty, as order of them is sometimes random.

Hope it helps you.

Jarek

Wysłane z iPhone'a

**Comment by wrkn4alivn** [comment]
No, I'm not using the device directly in Node-RED (only in the HA container, it's my Z-Wave dongle). But the way that hassio configures the Node-RED container, it pulls in all devices anyway because Node-RED supports serial I/O. 

IIUC from the previous bug comments, hassio isn't updating available devices in a timely fashion and so addon containers throw errors when starting up and not finding devices that hassio claims to have access to.... I'm just wondering if there is a way to flush devices, I tried removing all obsolete devices from `addon.json` but that didn't make a difference.
