### ISSUE TITLE
Problem Raspberry 3 B+, HASS.IO 0.82.1, Razberry Z-Wave Module

### ISSUE THREAD

**Issue by r1caux** [home-assistant/hassio#836]
Hi everyone

I'm desperate. I've been trying to set up my Z-Wave network for a few days now. For this I use the following hw:

- Raspberry 3 B+ with HASS.IO 0.82.1
- Razberry Board

**What I did:**
Added following lines to config.txt:
```
dtoverlay=pi3-disable-bt
enable_uart=1
```

Added zwave component to configuration.yaml:

```
zwave:
  usb_path: /dev/ttyAMA0
```

**Problem:**
`WARNING (Dummy-2) [openzwave] Z-Wave Notification DriverFailed : {'notificationType': 'DriverFailed', 'homeId': 0, 'nodeId': 255}`

**SSH:**
That's what I get for hassio hw info
```
{
    "result": "ok",
    "data": {
        "serial": [
            "/dev/ttyAMA0",
            "/dev/ttyS0"
        ],
        "input": [],
        "disk": [],
        "gpio": [
            "gpiochip128",
            "gpiochip0"
        ],
        "audio": {
            "0": {
                "name": "bcm2835_alsa - bcm2835 ALSA",
                "type": "ALSA",
                "devices": [
                    {
                        "chan_id": "0",
                        "chan_type": "digital audio playback"
                    },
                    {
                        "chan_id": "1",
                        "chan_type": "digital audio playback"
                    }
                ]
            }
        }
    }
}
```

But when I try to check the permission on ttyAMA0 it says there is no such file or directory (same for ttyS0)

```
core-ssh:~# ls -l /dev/ttyAMA0
ls: /dev/ttyAMA0: No such file or directory
```

They are not listed here either:
```
core-ssh:~# ls -l /dev
total 466
lrwxrwxrwx    1 root     root            13 Nov 24 23:04 fd -> /proc/self/fd
crw-rw-rw-    1 root     root        1,   7 Nov 24 23:04 full
-rwxr-xr-x    1 root     root        476800 Nov 21 13:52 init
drwxrwxrwt    2 root     root            40 Nov 24 23:04 mqueue
crw-rw-rw-    1 root     root        1,   3 Nov 24 23:04 null
lrwxrwxrwx    1 root     root             8 Nov 24 23:04 ptmx -> pts/ptmx
drwxr-xr-x    2 root     root             0 Nov 24 23:04 pts
crw-rw-rw-    1 root     root        1,   8 Nov 24 23:04 random
drwxrwxrwt    2 root     root            40 Nov 24 23:04 shm
lrwxrwxrwx    1 root     root            15 Nov 24 23:04 stderr -> /proc/self/fd/2
lrwxrwxrwx    1 root     root            15 Nov 24 23:04 stdin -> /proc/self/fd/0
lrwxrwxrwx    1 root     root            15 Nov 24 23:04 stdout -> /proc/self/fd/1
crw-rw-rw-    1 root     root        5,   0 Nov 24 23:04 tty
crw-rw-rw-    1 root     root        1,   9 Nov 24 23:04 urandom
crw-rw-rw-    1 root     root        1,   5 Nov 24 23:04 zero
```

Does anyone know what I could do to make this work?

**Comment by feeling001** [comment]
ttyAMA0 is the rpi's serial interface.

For zwave, you should use ttyACM0 ;-)

regards.

**Comment by baldus88** [comment]
Hi!
I have the same problem with my:
HassOS 2.12
Supervisor version 192

I have istalled the usb stick for zigbee protocol: ConBee_II
The zigbee is ok and go via deconz application installed on HASSIO.

I have alredy set this:
dtoverlay=pi3-disable-bt

I have added this line in the configuration file of hassio:
```
zwave:
  usb_path: /dev/ttyAMA0
```

core-ssh:/config# ls -l /dev/ttyAMA0
crw-rw----    1 root     audio     204,  64 Nov 17 15:24 /dev/ttyAMA0

But I have the same error when try to start the zwave protocol in configuration section:
**2019-11-17 15:25:05.608 Detail, contrlr, Notification: DriverFailed**

The ttyACM0 is not possibile to set because is utilize by Conbee USB.
This is the log deconz:
16:09:18:381 CTRL. 3.xx.xx.xx. dev /dev/ttyAMA0
16:09:18:473 COM: /dev/ttyACM0 / serialno: xxx
16:09:18:473 COM: --dev: /dev/ttyACM0 (ConBee II)

Thanks for the support!
