### ISSUE TITLE
temperUSB component failing to setup on hassio

### ISSUE THREAD

**Issue by cmsimike** [home-assistant/hassio#898]
**Home Assistant release with the issue:**

0.85.1
**Operating environment (HassOS/Generic):**

hassio on raspi3

```
Error while setting up platform temper
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/sensor/temper.py", line 44, in setup_platform
    temper_devices = get_temper_devices()
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/sensor/temper.py", line 33, in get_temper_devices
    return TemperHandler().get_devices()
  File "/usr/local/lib/python3.6/site-packages/temperusb/temper.py", line 420, in __init__
    usb.core.find(find_all=True, idVendor=vid, idProduct=pid)]
  File "/usr/local/lib/python3.6/site-packages/temperusb/temper.py", line 419, in <listcomp>
    self._devices += [TemperDevice(device) for device in \
  File "/usr/local/lib/python3.6/site-packages/temperusb/temper.py", line 95, in __init__
    self.lookup_sensor_count()
  File "/usr/local/lib/python3.6/site-packages/temperusb/temper.py", line 164, in lookup_sensor_count
    if (self._device.product == 'TEMPer1F_V1.3') or \
AttributeError: 'Device' object has no attribute 'product'
```

**Description of problem:**
I have verified that the usb shows up on the host pi, and the usb shows up when  i do an lsusb from within the homeassistant docker image, but I cannot setup the temper sensor.

**Comment by cmsimike** [comment]
Continuing to look into this, it seems like hassio doesn't list any usb name when issuing lsusb. usb.ids does seem to exist inside of hassio but doesn't seem to be used.

This breaks the temper usb sensor since the driver tries to access the device by name.

**Comment by pvizeli** [comment]
usb.ids are inside the container? otherwise it's fails

**Comment by JSkier21** [comment]
I am also having this issue, can this be re-opened please?

**Comment by user514** [comment]
Same here. Trying to get temper sensor online in hassio 0.103.6 says in log:

```
if (self._device.product == 'TEMPer1F_V1.3') or \
AttributeError: 'Device' object has no attribute 'product'
```

  ...and in command
hassio hw info
I get:

```
input:
- RDing TEMPer2_M12_V1.3
```

**Comment by Velby** [comment]
Has anyone managed to solve the issue? This doesn't seem to be caused by home assistant, if I get a shell on the docker container and run temper-poll I get the same error, it must be an issue with how the usb device is being handled by the container.
The strangest part is the temperature sensor is listed in lsusb in docker, I really have no idea where to go from here. I was getting the issue with hassio so I switched back to the standalone docker home assistant (which had temperusb working fine) and no I'm getting the same error there too!

The host machine (rpi3) can run temperusb just fine

**Comment by Velby** [comment]
Ok  I dug deeper and found the source of the issue:
temperusb requires the stable version of pyusb instead of the one being shipped with home assistant. I was able to do a temporary fix by:
- getting a shell on the home assistant container
- pip uninstall pysb
- pip install pyusb

This installed the stable version of pyusb and got everything working, but it'll have to be done everytime I deploy a new container
