### ISSUE TITLE
ERROR Can't upgrade install 0.89.1

### ISSUE THREAD

**Issue by gohassgo** [home-assistant/hassio#949]
**Home Assistant release with the issue:**
0.89.0b1 to 0.89.1

**Operating environment (HassOS/Generic):**
HassOS 1.7, Supervisor 148

**Supervisor logs:**
19-03-12 21:11:57 INFO (MainThread) [hassio.homeassistant] Update Home Assistant to version 0.89.1
19-03-12 21:11:57 INFO (SyncWorker_15) [hassio.docker.interface] Update Docker homeassistant/raspberrypi3-homeassistant:0.89.0b1 to homeassistant/raspberrypi3-homeassistant:0.89.1
19-03-12 21:11:57 INFO (SyncWorker_15) [hassio.docker.interface] Pull image homeassistant/raspberrypi3-homeassistant tag 0.89.1.
19-03-12 21:11:58 ERROR (SyncWorker_15) [hassio.docker.interface] Can't install homeassistant/raspberrypi3-homeassistant:0.89.1 -> 500 Server Error: Internal Server Error ("readlink /var/lib/docker/overlay2/l: invalid argument").
19-03-12 21:11:59 WARNING (MainThread) [hassio.homeassistant] Home Assistant is already running!
19-03-12 21:11:59 INFO (MainThread) [hassio.homeassistant] Successful run Home Assistant 0.89.1

**Description of problem:**
Upgrade via Hass.io fails. The error was similar with 0.89.0.

**Comment by libeco** [comment]
Although I don't have the exact same issue, I think mine is similar, so I wanted to notify the developers. In my case it happens when trying to install an add-on:
`19-03-17 14:31:23 INFO (SyncWorker_0) [hassio.docker.interface] Pull image hassioaddons/node-red-armhf tag 1.4.0.
19-03-17 14:31:25 ERROR (SyncWorker_0) [hassio.docker.interface] Can't install hassioaddons/node-red-armhf:1.4.0 -> 500 Server Error: Internal Server Error ("readlink /mnt/data/docker/overlay2/l: invalid argument").`

Btw, in this forum topic you can see more people have similar issues (including gohassgo): https://community.home-assistant.io/t/update-problem/103892

**Comment by gohassgo** [comment]
There are many posted issues with this error. A few of them point to an issue with Docker and being resolved with a Docker update at some point. 

My HassOS was on 1.70 and showed an update. I installed it and it is now running 2.10, but still have the error.

Here are a few...

https://github.com/home-assistant/hassio/issues/788
https://github.com/home-assistant/hassos/issues/152
